#!/bin/bash

# to install bash kernel
python -m bash_kernel.install

# to create a folder that is in the PATH
mkdir -p ~/.local/bin

# install fx
cd ~/.local/bin
curl https://fx.wtf/install.sh | sh
chmod +x ./fx

# install Miller
cd ~/.local/bin
wget https://github.com/johnkerl/miller/releases/download/v6.12.0/miller-6.12.0-linux-amd64.tar.gz
tar --strip-components=1 -xzf miller-6.12.0-linux-amd64.tar.gz
chmod +x ./mlr

# install duckdb
cd ~/.local/bin
wget https://github.com/duckdb/duckdb/releases/download/v1.1.0/duckdb_cli-linux-amd64.zip
unzip duckdb_cli-linux-amd64.zip
chmod +x ./duckdb

# install scrape-cli
cd ~/.local/bin
wget https://github.com/aborruso/scrape-cli/releases/download/v1.0/scrape
chmod +x ./scrape

# Install Zsh and Oh My Zsh
apt-get update && apt-get install --yes zsh

# Install Oh My Zsh silently
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Optional: install plugins for Oh My Zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Enable plugins in the .zshrc file
sed -i 's/plugins=(git)/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/' ~/.zshrc

# You can start zsh manually later, or add a note to users to run 'zsh' in the terminal.
