#!/bin/bash

# to install bash kernel
python -m bash_kernel.install

# Install Zsh and Oh My Zsh
apt-get update && apt-get install --yes zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Cambia la shell predefinita in Zsh
chsh -s $(which zsh)

# Optional: install plugins for Oh My Zsh (e.g., git, fzf)
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Enable plugins in the .zshrc file
sed -i 's/plugins=(git)/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/' ~/.zshrc

# Source the .zshrc to apply changes
source ~/.zshrc
